# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/591e65f4-7622-4023-bbda-d67ad166b1fb";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard"  ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4d404d48-acde-4f82-bf30-8ecee12d3c67";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FCA9-6285";
      fsType = "vfat";
      options = [ "noatime" "nodiratime" "discard"  ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4c191004-8cf5-4e39-a330-2b35557cfb45"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
